FROM python:3.7-slim
ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./


###  MONGODB ENVS
ARG MONGO_URI
ENV MONGO_URI=$MONGO_URI

### GOOGLE CLOUD ENVS
ARG GOOGLE_PROJECT_ID
ARG GOOGLE_PUBSUB_TOPIC_NAME
ARG GOOGLE_APPLICATION_CREDENTIALS

ENV GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
ENV GOOGLE_PUBSUB_TOPIC_NAME=$GOOGLE_PUBSUB_TOPIC_NAME

ENV GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/credentials.json

RUN pip install -r requirements.txt  &&  python -m unittest test/*.py


CMD ["python", "application.py"]